#
# Copyright (c) 2014 Actions Semiconductor Co., Ltd.
#
# Author: Yixun Lan <yixun.lan@gmail.com>

# Licensed under GPLv2

ccflags-$(CONFIG_ARCH_MULTIPLATFORM) := -I$(srctree)/$(src)/include

obj-$(CONFIG_ARCH_OWL) += owl.o cpu-owl.o common-owl.o timer-owl.o
